// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VillaAPI.Data;

#nullable disable

namespace VillaAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VillaAPI.Model.Villa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Amenity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Occupancy")
                        .HasColumnType("int");

                    b.Property<double>("Rate")
                        .HasColumnType("float");

                    b.Property<int>("Sqft")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Villas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amenity = "Ocean view, Wi-Fi",
                            CreatedDate = new DateTime(2024, 11, 2, 9, 32, 31, 618, DateTimeKind.Local).AddTicks(3757),
                            Details = "A beautiful villa by the beach.",
                            ImageUrl = "",
                            Name = "Beachfront Villa",
                            Occupancy = 4,
                            Rate = 300.0,
                            Sqft = 600,
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Amenity = "Mountain view, Fireplace",
                            CreatedDate = new DateTime(2024, 11, 2, 9, 32, 31, 618, DateTimeKind.Local).AddTicks(3770),
                            Details = "A cozy villa nestled in the mountains.",
                            ImageUrl = "",
                            Name = "Mountain Villa",
                            Occupancy = 5,
                            Rate = 350.0,
                            Sqft = 700,
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Amenity = "City view, Gym access",
                            CreatedDate = new DateTime(2024, 11, 2, 9, 32, 31, 618, DateTimeKind.Local).AddTicks(3771),
                            Details = "A luxurious villa in the heart of the city.",
                            ImageUrl = "",
                            Name = "City Villa",
                            Occupancy = 3,
                            Rate = 400.0,
                            Sqft = 500,
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            Amenity = "Garden, Outdoor pool",
                            CreatedDate = new DateTime(2024, 11, 2, 9, 32, 31, 618, DateTimeKind.Local).AddTicks(3773),
                            Details = "A charming villa in the countryside.",
                            ImageUrl = "",
                            Name = "Countryside Villa",
                            Occupancy = 6,
                            Rate = 250.0,
                            Sqft = 800,
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            Amenity = "Lake view, Canoe access",
                            CreatedDate = new DateTime(2024, 11, 2, 9, 32, 31, 618, DateTimeKind.Local).AddTicks(3774),
                            Details = "A serene villa by the lake.",
                            ImageUrl = "",
                            Name = "Lake Villa",
                            Occupancy = 2,
                            Rate = 280.0,
                            Sqft = 450,
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            Amenity = "Desert view, Air conditioning",
                            CreatedDate = new DateTime(2024, 11, 2, 9, 32, 31, 618, DateTimeKind.Local).AddTicks(3775),
                            Details = "A unique villa in the desert.",
                            ImageUrl = "",
                            Name = "Desert Villa",
                            Occupancy = 4,
                            Rate = 320.0,
                            Sqft = 650,
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            Amenity = "Forest view, Fireplace",
                            CreatedDate = new DateTime(2024, 11, 2, 9, 32, 31, 618, DateTimeKind.Local).AddTicks(3777),
                            Details = "A rustic villa surrounded by trees.",
                            ImageUrl = "",
                            Name = "Forest Villa",
                            Occupancy = 4,
                            Rate = 310.0,
                            Sqft = 600,
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            Amenity = "Ocean view, Private beach",
                            CreatedDate = new DateTime(2024, 11, 2, 9, 32, 31, 618, DateTimeKind.Local).AddTicks(3778),
                            Details = "An exotic villa on a private island.",
                            ImageUrl = "",
                            Name = "Island Villa",
                            Occupancy = 8,
                            Rate = 500.0,
                            Sqft = 1000,
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            Amenity = "Jungle view, Outdoor shower",
                            CreatedDate = new DateTime(2024, 11, 2, 9, 32, 31, 618, DateTimeKind.Local).AddTicks(3779),
                            Details = "An adventurous villa in the jungle.",
                            ImageUrl = "",
                            Name = "Jungle Villa",
                            Occupancy = 3,
                            Rate = 270.0,
                            Sqft = 550,
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 10,
                            Amenity = "Smart home features, Pool",
                            CreatedDate = new DateTime(2024, 11, 2, 9, 32, 31, 618, DateTimeKind.Local).AddTicks(3781),
                            Details = "A sleek, modern villa with all amenities.",
                            ImageUrl = "",
                            Name = "Modern Villa",
                            Occupancy = 5,
                            Rate = 450.0,
                            Sqft = 700,
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
